USE [master]
GO
/****** Object:  Database [BibALEX]    Script Date: 15/08/2024 19:13:03 ******/
CREATE DATABASE [BibALEX]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BibALEX', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BibALEX.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BibALEX_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BibALEX_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BibALEX] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BibALEX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BibALEX] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BibALEX] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BibALEX] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BibALEX] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BibALEX] SET ARITHABORT OFF 
GO
ALTER DATABASE [BibALEX] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BibALEX] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BibALEX] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BibALEX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BibALEX] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BibALEX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BibALEX] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BibALEX] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BibALEX] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BibALEX] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BibALEX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BibALEX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BibALEX] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BibALEX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BibALEX] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BibALEX] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BibALEX] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BibALEX] SET RECOVERY FULL 
GO
ALTER DATABASE [BibALEX] SET  MULTI_USER 
GO
ALTER DATABASE [BibALEX] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BibALEX] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BibALEX] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BibALEX] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BibALEX] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BibALEX] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BibALEX', N'ON'
GO
ALTER DATABASE [BibALEX] SET QUERY_STORE = ON
GO
ALTER DATABASE [BibALEX] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BibALEX]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 15/08/2024 19:13:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[CID] [int] IDENTITY(1,1) NOT NULL,
	[CNAME] [nvarchar](32) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Channel]    Script Date: 15/08/2024 19:13:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Channel](
	[CHID] [int] IDENTITY(1,1) NOT NULL,
	[CHNAME] [nvarchar](max) NOT NULL,
	[CHLOGO] [nvarchar](max) NULL,
	[CHDESC] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[CHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ContributesToChannel]    Script Date: 15/08/2024 19:13:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ContributesToChannel](
	[UID] [int] NOT NULL,
	[CHID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UID] ASC,
	[CHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Playlist]    Script Date: 15/08/2024 19:13:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Playlist](
	[PID] [int] IDENTITY(1,1) NOT NULL,
	[CHID] [int] NULL,
	[PTITLE] [nvarchar](32) NOT NULL,
	[PTHUMBNAIL] [nvarchar](max) NULL,
	[PDESC] [nvarchar](max) NULL,
	[VID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 15/08/2024 19:13:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UID] [int] IDENTITY(1,1) NOT NULL,
	[FNAME] [nvarchar](32) NOT NULL,
	[LNAME] [nvarchar](32) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Video]    Script Date: 15/08/2024 19:13:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Video](
	[VIDID] [int] IDENTITY(1,1) NOT NULL,
	[CHID] [int] NOT NULL,
	[VIDPATH] [nvarchar](max) NOT NULL,
	[VTHUMBNAIL] [nvarchar](max) NULL,
	[VTITLE] [nvarchar](max) NOT NULL,
	[VDESC] [nvarchar](max) NULL,
	[UPLOADDATE] [datetime] NULL,
	[PUBLISHDATE] [datetime] NULL,
	[CURRENTVIEWS] [int] NULL,
	[TRANSCRIPT] [nvarchar](max) NULL,
	[VID] [int] NULL,
	[CID] [int] NULL,
	[PID] [int] NOT NULL,
	[DURATION] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[VIDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Visibility]    Script Date: 15/08/2024 19:13:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Visibility](
	[VID] [int] IDENTITY(1,1) NOT NULL,
	[VNAME] [nvarchar](16) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[VID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ContributesToChannel]  WITH CHECK ADD FOREIGN KEY([CHID])
REFERENCES [dbo].[Channel] ([CHID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ContributesToChannel]  WITH CHECK ADD FOREIGN KEY([UID])
REFERENCES [dbo].[Users] ([UID])
GO
ALTER TABLE [dbo].[Playlist]  WITH CHECK ADD FOREIGN KEY([CHID])
REFERENCES [dbo].[Channel] ([CHID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Playlist]  WITH CHECK ADD FOREIGN KEY([VID])
REFERENCES [dbo].[Visibility] ([VID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Video]  WITH CHECK ADD FOREIGN KEY([CHID])
REFERENCES [dbo].[Channel] ([CHID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Video]  WITH CHECK ADD FOREIGN KEY([CID])
REFERENCES [dbo].[Category] ([CID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Video]  WITH CHECK ADD FOREIGN KEY([PID])
REFERENCES [dbo].[Playlist] ([PID])
GO
ALTER TABLE [dbo].[Video]  WITH CHECK ADD FOREIGN KEY([VID])
REFERENCES [dbo].[Visibility] ([VID])
ON DELETE SET NULL
GO
USE [master]
GO
ALTER DATABASE [BibALEX] SET  READ_WRITE 
GO
